// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using opentools.Models;

#nullable disable

namespace opentools.Migrations
{
    [DbContext(typeof(OtNoteItemContext))]
    partial class OtNoteItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("opentools.Models.OtNoteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OtCompletedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OtCreateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OtIsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtNoteDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtNoteName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OtNoteItem");
                });
#pragma warning restore 612, 618
        }
    }
}
